title: InnovAnon-Inc
email: InnovAnon-Inc@gmx.com
description: >- 
  This project is a package repository which simplify using custom binaries properly, instead of some other way.
baseurl: ""
url: "https://InnovAnon-Inc.github.io/ppa"
github_username: InnovAnon-Inc

# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - tools/
  - doc/

