title: InnovAnon-Inc
email: InnovAnon-Inc@gmx.com
description: >- 
  This project is a script which polls the AWS Metadata Service looking for a termination warning, and triggers a response.
baseurl: ""
url: "https://InnovAnon-Inc.github.io/ppa"
github_username: InnovAnon-Inc

# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - tools/
  - doc/

